export interface ProductOffer {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  features: string[];
  creditMin: number;
  creditMax: number;
  incomeMin: number;
  studentFriendly: boolean;
  businessOwnerFriendly: boolean;
  payout: number;
  apr?: string;
  annualFee?: string;
  signupBonus?: string;
  tags: string[];
  affiliateUrl: string;
  logoUrl?: string;
  cardImage?: string;
  issuerIcon?: string; // Lucide icon name for card issuer
  cardColor?: string; // Gradient or solid color for card display
  rating: number;
}

export const CATEGORIES = {
  PRIMARY: [
    { id: 'credit-cards', name: 'Credit Cards', icon: 'CreditCard', description: 'AI-matched cards based on your profile and goals' },
    { id: 'personal-loans', name: 'Personal Loans', icon: 'Wallet', description: 'Compare lenders for consolidation and lower APRs' },
    { id: 'business-funding', name: 'Business Funding', icon: 'Building2', description: 'Business cards, lines of credit, and startup capital' },
    { id: 'banking', name: 'Banking', icon: 'Landmark', description: 'High-yield savings, checking, and cash tools' },
    { id: 'insurance', name: 'Insurance', icon: 'Shield', description: 'Auto, home, and life insurance quotes' },
    { id: 'investing', name: 'Investing', icon: 'TrendingUp', description: 'Brokerages, robo-advisors, and long-term tools' },
  ],
  SECONDARY: [
    { id: 'refinancing', name: 'Refinancing', icon: 'RefreshCw', description: 'Rate Watch monitors markets 24/7 and alerts you when refinancing makes sense' },
    { id: 'credit-builder', name: 'Credit Builder', icon: 'Target', description: 'Build or rebuild your credit score - no credit pull needed' },
    { id: 'student-finance', name: 'Student Finance', icon: 'GraduationCap', description: 'Student loans, refinancing, and banking' },
    { id: 'renters-insurance', name: 'Renters Insurance', icon: 'Home', description: 'Affordable coverage starting at $5/month' },
    { id: 'estate-planning', name: 'Estate Planning', icon: 'FileText', description: 'Wills, trusts, and legacy protection tools' },
  ],
  SUPPORTING: [
    { id: 'tax-tools', name: 'Tax Tools', icon: 'Calculator', description: 'Free and paid tax filing solutions' },
    { id: 'identity-security', name: 'Identity & Security', icon: 'Lock', description: 'Identity protection and credit monitoring' },
    { id: 'budgeting-apps', name: 'Budgeting Apps', icon: 'PieChart', description: 'Subscription trackers and money management' },
    { id: 'rewards-cashback', name: 'Cashback Apps', icon: 'Gift', description: 'Free cashback apps with instant rewards' },
    { id: 'micro-investing', name: 'Micro-Investing', icon: 'Coins', description: 'Start investing with just $1-$5' },
  ],
  FLAGSHIP: [
    { id: 'real-estate', name: 'Real Estate Concierge', icon: 'Home', description: 'Our flagship luxury real estate + RBO system' },
  ],
} as const;

export const SUBCATEGORIES: Record<string, string[]> = {
  'credit-cards': [
    'Best Card Picks',
    'Cash Back Cards',
    'Travel & Points Cards',
    '0% APR Cards',
    'Student Cards',
    'Secured Cards',
    'Business Credit Cards',
    'Credit Builder Cards',
    'No Credit Check Cards',
  ],
  'personal-loans': [
    'Debt Consolidation',
    'Bad Credit Loans',
    'Emergency Loans',
    'Installment Loans',
    'Soft-Pull Pre-Qualification',
    'Student Loan Refinancing',
    'Medical/Dental Financing',
  ],
  'business-funding': [
    'Merchant Cash Advance',
    'Business Line of Credit',
    'Business Term Loans',
    'Startup Capital',
    'Equipment Financing',
    'Invoice Factoring',
    'Revenue-Based Financing',
    'E-Commerce Seller Funding',
  ],
  'banking': [
    'High-Yield Savings',
    'Checking Accounts',
    'Fintech Banks',
    'Debit Cards',
    'Cash Management Accounts',
    'Business Banking',
    'Teen/Student Banking',
  ],
  'insurance': [
    'Auto Insurance',
    'Home Insurance',
    'Renters Insurance',
    'Life Insurance',
    'Health Insurance',
    'Pet Insurance',
    'Business Insurance',
    'Travel Insurance',
  ],
  'investing': [
    'Stock Trading Apps',
    'Robo-Advisors',
    'Long-Term Investing',
    'Crypto Platforms',
    'IRA/Roth IRA',
    'Real Estate Investing',
    'Micro-Investment Apps',
  ],
  'credit-builder': [
    'Secured Cards',
    'Credit Builder Cards',
    'Credit Builder Loans',
    'Rent Reporting',
    'Utility Reporting',
    'Subscription Builders',
  ],
  'student-finance': [
    'Student Loan Refinancing',
    'Private Student Loans',
    'Tuition Financing',
    'FAFSA Assistance',
    'Scholarship Matching',
    'Student Banking',
    'Student Credit Cards',
  ],
  'tax-tools': [
    'Free Tax Filing',
    'Paid Tax Filing',
    'Pro-Assisted Filing',
    'Tax Refund Advance',
  ],
  'identity-security': [
    'Identity Protection',
    'Credit Monitoring',
    'Password Managers',
    'VPN Services',
  ],
  'budgeting-apps': [
    'Budgeting Apps',
    'Bill Negotiation',
    'Subscription Managers',
    'Cash Back Apps',
    'Round-Up Savings',
  ],
  'rewards-cashback': [
    'Cashback Apps',
    'Browser Extensions',
    'Gas Cashback',
    'Receipt Scanning',
    'Shopping Rewards',
  ],
  'renters-insurance': [
    'AI-Powered Insurance',
    'Traditional Carriers',
    'Bundle Options',
  ],
  'estate-planning': [
    'Online Wills',
    'Living Trusts',
    'Legal Document Services',
  ],
  'micro-investing': [
    'Round-Up Apps',
    'Beginner Platforms',
    'Free Stock Offers',
  ],
  'refinancing': [
    'Mortgage Refinance',
    'Auto Loan Refinance',
    'Student Loan Refinance',
    'Personal Loan Refinance',
    'Cash-Out Refinance',
  ],
  'real-estate': [
    'Reverse Buyer Origination',
    'Home Buyer Tools',
    'Luxury Concierge',
    'Market Discovery',
    'Pre-Approval Guidance',
  ],
};

export const SAMPLE_OFFERS: ProductOffer[] = [
  {
    id: 'chase-sapphire-preferred',
    name: 'Chase Sapphire Preferred',
    category: 'credit-cards',
    subcategory: 'Travel & Points Cards',
    description: 'Premium travel rewards card with flexible point redemption and travel protections',
    features: ['60,000 bonus points after $4,000 spend', '2X points on travel and dining', 'No foreign transaction fees', 'Trip cancellation insurance'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 40000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '21.49% - 28.49%',
    annualFee: '$95',
    signupBonus: '60,000 points ($750 value)',
    tags: ['travel', 'points', 'premium'],
    affiliateUrl: '#',
    issuerIcon: 'Landmark',
    cardColor: 'from-blue-900 via-blue-800 to-blue-950',
    rating: 4.8,
  },
  {
    id: 'citi-double-cash',
    name: 'Citi Double Cash Card',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn 2% cash back on every purchase - 1% when you buy, 1% when you pay',
    features: ['2% cash back on all purchases', 'No annual fee', 'No category restrictions', '0% intro APR for 18 months'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '18.49% - 28.49%',
    annualFee: '$0',
    signupBonus: 'None',
    tags: ['cashback', 'no-fee', 'simple'],
    affiliateUrl: '#',
    issuerIcon: 'Building2',
    cardColor: 'from-sky-600 via-sky-500 to-sky-700',
    rating: 4.6,
  },
  {
    id: 'discover-it-secured',
    name: 'Discover it Secured',
    category: 'credit-cards',
    subcategory: 'Secured Cards',
    description: 'Build credit with a secured card that matches your cash back at the end of year one',
    features: ['2% cash back at restaurants and gas stations', 'Cashback match first year', 'No annual fee', 'Free FICO score'],
    creditMin: 300,
    creditMax: 650,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 50,
    apr: '28.24%',
    annualFee: '$0',
    signupBonus: 'Cashback Match',
    tags: ['secured', 'credit-builder', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'CircleDot',
    cardColor: 'from-orange-500 via-orange-400 to-orange-600',
    rating: 4.5,
  },
  {
    id: 'wells-fargo-reflect',
    name: 'Wells Fargo Reflect Card',
    category: 'credit-cards',
    subcategory: '0% APR Cards',
    description: 'One of the longest 0% intro APR periods available - up to 21 months on purchases and balance transfers',
    features: ['0% intro APR for 21 months', 'Up to $600 cell phone protection', 'No annual fee', 'My Wells Fargo Deals cashback'],
    creditMin: 690,
    creditMax: 850,
    incomeMin: 30000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '17.74% - 28.49%',
    annualFee: '$0',
    signupBonus: 'None',
    tags: ['balance-transfer', '0-apr', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'Banknote',
    cardColor: 'from-red-700 via-red-600 to-red-800',
    rating: 4.5,
  },
  {
    id: 'chase-freedom-unlimited',
    name: 'Chase Freedom Unlimited',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn unlimited 1.5% cash back on all purchases plus bonus categories up to 5%',
    features: ['$200 bonus after $500 spend', '5% on travel via Chase', '3% on dining and drugstores', '1.5% on everything else'],
    creditMin: 690,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 125,
    apr: '18.49% - 27.99%',
    annualFee: '$0',
    signupBonus: '$200 cash bonus',
    tags: ['cashback', 'no-fee', 'flexible'],
    affiliateUrl: '#',
    issuerIcon: 'Landmark',
    cardColor: 'from-slate-700 via-slate-600 to-slate-800',
    rating: 5.0,
  },
  {
    id: 'discover-it-cash-back',
    name: 'Discover it Cash Back',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn 5% cash back in rotating quarterly categories and get your cashback matched the first year',
    features: ['5% rotating categories (up to quarterly max)', 'Unlimited Cashback Match year one', '0% APR for 18 months on balance transfers', 'No annual fee'],
    creditMin: 690,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '17.74% - 26.74%',
    annualFee: '$0',
    signupBonus: 'Cashback Match (doubles first year)',
    tags: ['cashback', 'rotating-categories', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'CircleDot',
    cardColor: 'from-orange-600 via-orange-500 to-amber-600',
    rating: 4.9,
  },
  {
    id: 'citi-simplicity',
    name: 'Citi Simplicity Card',
    category: 'credit-cards',
    subcategory: '0% APR Cards',
    description: 'The card with no late fees ever - plus one of the longest 0% intro APR periods on balance transfers',
    features: ['0% intro APR for 21 months on balance transfers', '0% intro APR for 12 months on purchases', 'No late fees ever', 'No penalty rate'],
    creditMin: 690,
    creditMax: 850,
    incomeMin: 30000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 75,
    apr: '17.74% - 28.49%',
    annualFee: '$0',
    signupBonus: 'None',
    tags: ['balance-transfer', '0-apr', 'no-late-fees'],
    affiliateUrl: '#',
    issuerIcon: 'Building2',
    cardColor: 'from-blue-600 via-blue-500 to-cyan-600',
    rating: 4.5,
  },
  {
    id: 'amex-blue-cash-everyday',
    name: 'Blue Cash Everyday Card from American Express',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn 3% cash back at U.S. supermarkets, gas stations, and online retail purchases',
    features: ['$200 statement credit after $2,000 spend', '3% at supermarkets (up to $6K/year)', '3% at gas stations', '3% on online retail'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '18.74% - 29.74%',
    annualFee: '$0',
    signupBonus: '$200 statement credit',
    tags: ['cashback', 'groceries', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'CreditCard',
    cardColor: 'from-blue-500 via-blue-400 to-sky-500',
    rating: 4.9,
  },
  {
    id: 'capital-one-quicksilver',
    name: 'Capital One Quicksilver Cash Rewards',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn unlimited 1.5% cash back on every purchase with no rotating categories to track',
    features: ['$200 cash bonus after $500 spend', 'Unlimited 1.5% cash back', '0% intro APR for 15 months', 'No foreign transaction fees'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '19.99% - 29.99%',
    annualFee: '$0',
    signupBonus: '$200 cash bonus',
    tags: ['cashback', 'simple', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'Zap',
    cardColor: 'from-slate-800 via-slate-700 to-zinc-800',
    rating: 4.7,
  },
  {
    id: 'capital-one-venture-x',
    name: 'Capital One Venture X Rewards',
    category: 'credit-cards',
    subcategory: 'Travel & Points Cards',
    description: 'Premium travel card with 75,000 mile bonus, airport lounge access, and $300 travel credit',
    features: ['75,000 bonus miles after $4,000 spend', '10X miles on hotels via Capital One Travel', 'Priority Pass lounge access', '$300 annual travel credit'],
    creditMin: 740,
    creditMax: 850,
    incomeMin: 75000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 300,
    apr: '19.99% - 29.99%',
    annualFee: '$395',
    signupBonus: '75,000 miles ($750+ value)',
    tags: ['travel', 'premium', 'lounge-access'],
    affiliateUrl: '#',
    issuerIcon: 'Zap',
    cardColor: 'from-slate-900 via-slate-800 to-black',
    rating: 4.9,
  },
  {
    id: 'amex-gold',
    name: 'American Express Gold Card',
    category: 'credit-cards',
    subcategory: 'Travel & Points Cards',
    description: 'Earn 4X points at restaurants and supermarkets - the ultimate foodie rewards card',
    features: ['60,000 bonus points after $6,000 spend', '4X at restaurants worldwide', '4X at U.S. supermarkets', '$120 dining credit + $120 Uber Cash'],
    creditMin: 700,
    creditMax: 850,
    incomeMin: 50000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '21.74% - 29.74%',
    annualFee: '$250',
    signupBonus: '60,000 points ($600+ value)',
    tags: ['travel', 'dining', 'points'],
    affiliateUrl: '#',
    issuerIcon: 'CreditCard',
    cardColor: 'from-amber-500 via-yellow-500 to-amber-600',
    rating: 4.8,
  },
  {
    id: 'chase-ink-business-preferred',
    name: 'Chase Ink Business Preferred',
    category: 'credit-cards',
    subcategory: 'Business Credit Cards',
    description: 'Earn 100,000 bonus points and 3X on travel, shipping, internet, cable, and phone services',
    features: ['100,000 bonus points after $8,000 spend', '3X on travel and select business categories', 'No foreign transaction fees', 'Trip cancellation insurance'],
    creditMin: 700,
    creditMax: 850,
    incomeMin: 50000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 350,
    apr: '20.99% - 26.99%',
    annualFee: '$95',
    signupBonus: '100,000 points ($1,250 value)',
    tags: ['business', 'travel', 'points'],
    affiliateUrl: '#',
    issuerIcon: 'Landmark',
    cardColor: 'from-indigo-900 via-indigo-800 to-blue-900',
    rating: 4.9,
  },
  {
    id: 'capital-one-savor-one',
    name: 'Capital One SavorOne Cash Rewards',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn unlimited 3% cash back on dining, entertainment, streaming, and groceries',
    features: ['$200 cash bonus after $500 spend', '3% on dining and entertainment', '3% at grocery stores', '3% on streaming services'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '19.99% - 29.99%',
    annualFee: '$0',
    signupBonus: '$200 cash bonus',
    tags: ['cashback', 'dining', 'entertainment'],
    affiliateUrl: '#',
    issuerIcon: 'Zap',
    cardColor: 'from-violet-700 via-purple-600 to-violet-800',
    rating: 4.7,
  },
  {
    id: 'chase-sapphire-reserve',
    name: 'Chase Sapphire Reserve',
    category: 'credit-cards',
    subcategory: 'Travel & Points Cards',
    description: 'The ultimate premium travel card with Priority Pass lounge access and $300 annual travel credit',
    features: ['60,000 bonus points after $4,000 spend', '3X on travel and dining', 'Priority Pass lounge access', '$300 annual travel credit'],
    creditMin: 740,
    creditMax: 850,
    incomeMin: 75000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 350,
    apr: '22.49% - 29.49%',
    annualFee: '$550',
    signupBonus: '60,000 points ($900 value)',
    tags: ['travel', 'premium', 'lounge-access'],
    affiliateUrl: '#',
    issuerIcon: 'Landmark',
    cardColor: 'from-slate-900 via-blue-900 to-slate-950',
    rating: 4.8,
  },
  {
    id: 'discover-it-student',
    name: 'Discover it Student Cash Back',
    category: 'credit-cards',
    subcategory: 'Student Cards',
    description: 'Build credit as a student with 5% rotating categories and Good Grade Rewards',
    features: ['$20 statement credit for GPA 3.0+', '5% rotating quarterly categories', 'Cashback Match first year', 'No annual fee'],
    creditMin: 0,
    creditMax: 670,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 50,
    apr: '18.74% - 27.74%',
    annualFee: '$0',
    signupBonus: 'Good Grade Rewards + Cashback Match',
    tags: ['student', 'cashback', 'credit-builder'],
    affiliateUrl: '#',
    issuerIcon: 'CircleDot',
    cardColor: 'from-teal-600 via-teal-500 to-emerald-600',
    rating: 4.6,
  },
  {
    id: 'bank-of-america-customized-cash',
    name: 'Bank of America Customized Cash Rewards',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Choose your own 3% category - gas, online shopping, dining, travel, drug stores, or home improvement',
    features: ['$200 cash bonus after $1,000 spend', '3% in category of choice', '2% at grocery stores', 'Preferred Rewards boost up to 75%'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '17.74% - 27.74%',
    annualFee: '$0',
    signupBonus: '$200 cash bonus',
    tags: ['cashback', 'customizable', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'Building',
    cardColor: 'from-red-600 via-red-500 to-rose-600',
    rating: 4.6,
  },
  {
    id: 'wells-fargo-active-cash',
    name: 'Wells Fargo Active Cash Card',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn unlimited 2% cash rewards on purchases - one of the highest flat-rate cards available',
    features: ['$200 cash bonus after $500 spend', 'Unlimited 2% cash back', '0% intro APR for 12 months', 'Up to $600 cell phone protection'],
    creditMin: 690,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '18.74% - 28.99%',
    annualFee: '$0',
    signupBonus: '$200 cash bonus',
    tags: ['cashback', 'simple', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'Banknote',
    cardColor: 'from-red-800 via-red-700 to-rose-800',
    rating: 4.8,
  },
  {
    id: 'sofi-personal-loan',
    name: 'SoFi Personal Loan',
    category: 'personal-loans',
    subcategory: 'Debt Consolidation',
    description: 'Low-rate personal loans with no fees and unemployment protection',
    features: ['No origination fees', 'No prepayment penalties', 'Unemployment protection', 'Rate discount with autopay'],
    creditMin: 680,
    creditMax: 850,
    incomeMin: 45000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 150,
    apr: '8.99% - 25.81%',
    tags: ['low-rate', 'no-fees', 'debt-consolidation'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'upstart-personal-loan',
    name: 'Upstart Personal Loan',
    category: 'personal-loans',
    subcategory: 'Bad Credit Loans',
    description: 'AI-powered lending that looks beyond credit score',
    features: ['Consider education and employment', 'Fast funding', 'Fixed rates', 'Accepts lower credit scores'],
    creditMin: 580,
    creditMax: 850,
    incomeMin: 20000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '7.80% - 35.99%',
    tags: ['bad-credit', 'ai-powered', 'fast-funding'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'bluevine-loc',
    name: 'BlueVine Business Line of Credit',
    category: 'business-funding',
    subcategory: 'Business Line of Credit',
    description: 'Flexible business financing with fast approval and competitive rates',
    features: ['Up to $250,000 credit line', 'Draw funds as needed', 'Only pay for what you use', 'Fast online application'],
    creditMin: 625,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 300,
    apr: '7.80% - 25.00%',
    tags: ['business', 'line-of-credit', 'flexible'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'ondeck-term-loan',
    name: 'OnDeck Business Term Loan',
    category: 'business-funding',
    subcategory: 'Business Term Loans',
    description: 'Fast business loans with same-day funding available',
    features: ['$5K to $250K loans', 'Same-day funding possible', 'Fixed daily/weekly payments', 'Build business credit'],
    creditMin: 600,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 250,
    apr: '29.9% - 97.3%',
    tags: ['business', 'fast-funding', 'term-loan'],
    affiliateUrl: '#',
    rating: 4.2,
  },
  {
    id: 'chime-checking',
    name: 'Chime Checking Account',
    category: 'banking',
    subcategory: 'Fintech Banks',
    description: 'Fee-free online checking with early direct deposit and overdraft protection',
    features: ['No monthly fees', 'Get paid early', 'SpotMe overdraft up to $200', '60,000+ fee-free ATMs'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 80,
    tags: ['no-fee', 'fintech', 'early-deposit'],
    affiliateUrl: '#',
    issuerIcon: 'Sparkles',
    cardColor: 'from-green-500 via-green-400 to-emerald-500',
    rating: 4.6,
  },
  {
    id: 'sofi-savings',
    name: 'SoFi Checking & Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'High-yield savings with checking features and no account fees',
    features: ['4.50% APY on savings', 'No account fees', 'Early direct deposit', 'Fee-free overdraft'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '4.50% APY',
    tags: ['high-yield', 'no-fee', 'checking-savings'],
    affiliateUrl: '#',
    issuerIcon: 'Zap',
    cardColor: 'from-purple-600 via-purple-500 to-indigo-600',
    rating: 4.7,
  },
  {
    id: 'cit-bank-platinum-savings',
    name: 'CIT Bank Platinum Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Top-tier APY with $5,000 minimum balance and up to $300 welcome bonus',
    features: ['3.75% APY with $5,000+ balance', 'Up to $300 welcome bonus', 'FDIC insured', 'No monthly service fees'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 150,
    apr: '3.75% APY',
    signupBonus: 'Up to $300 bonus',
    tags: ['high-yield', 'bonus', 'fdic-insured'],
    affiliateUrl: '#',
    issuerIcon: 'Building2',
    cardColor: 'from-emerald-600 via-emerald-500 to-teal-600',
    rating: 4.5,
  },
  {
    id: 'capital-one-360-savings',
    name: 'Capital One 360 Performance Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'No minimum balance required with competitive APY from a trusted brand',
    features: ['3.40% APY', 'No minimum balance', 'No monthly fees', 'Easy mobile app'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '3.40% APY',
    tags: ['high-yield', 'no-minimum', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'Zap',
    cardColor: 'from-red-600 via-red-500 to-rose-600',
    rating: 4.3,
  },
  {
    id: 'marcus-savings',
    name: 'Marcus by Goldman Sachs Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'High-yield savings from Goldman Sachs with no fees and no minimums',
    features: ['4.00% APY', 'No minimum deposit', 'No transaction fees', 'FDIC insured'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '4.00% APY',
    tags: ['high-yield', 'no-minimum', 'trusted'],
    affiliateUrl: '#',
    issuerIcon: 'Landmark',
    cardColor: 'from-slate-800 via-slate-700 to-zinc-800',
    rating: 4.6,
  },
  {
    id: 'discover-savings',
    name: 'Discover Online Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Competitive rates with 24/7 US-based customer service',
    features: ['4.10% APY', 'No minimum balance', 'No monthly fees', '24/7 US customer service'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 80,
    apr: '4.10% APY',
    tags: ['high-yield', 'no-minimum', 'customer-service'],
    affiliateUrl: '#',
    issuerIcon: 'CircleDot',
    cardColor: 'from-orange-600 via-orange-500 to-amber-600',
    rating: 4.5,
  },
  {
    id: 'amex-hysa',
    name: 'American Express High-Yield Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Trusted brand with competitive APY and no minimum balance requirements',
    features: ['3.90% APY', 'No minimum balance', 'No monthly fees', 'Easy funds transfer'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '3.90% APY',
    tags: ['high-yield', 'trusted-brand', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'CreditCard',
    cardColor: 'from-blue-600 via-blue-500 to-sky-600',
    rating: 4.4,
  },
  {
    id: 'barclays-savings',
    name: 'Barclays Online Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Strong APY with no minimum opening deposit from global banking leader',
    features: ['4.00% APY', 'No minimum opening deposit', 'No monthly maintenance fees', 'FDIC insured'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 80,
    apr: '4.00% APY',
    tags: ['high-yield', 'no-minimum', 'global-bank'],
    affiliateUrl: '#',
    issuerIcon: 'Building',
    cardColor: 'from-cyan-600 via-cyan-500 to-teal-600',
    rating: 4.4,
  },
  {
    id: 'synchrony-savings',
    name: 'Synchrony High-Yield Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Consistently competitive rates with ATM card access',
    features: ['4.25% APY', 'No minimum balance', 'Optional ATM card', 'Perks rewards program'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '4.25% APY',
    tags: ['high-yield', 'atm-access', 'perks'],
    affiliateUrl: '#',
    issuerIcon: 'Banknote',
    cardColor: 'from-violet-600 via-violet-500 to-purple-600',
    rating: 4.3,
  },
  {
    id: 'wealthfront-cash',
    name: 'Wealthfront Cash Account',
    category: 'banking',
    subcategory: 'Cash Management',
    description: 'High APY cash account with investing features and FDIC coverage up to $8M',
    features: ['4.00% APY', 'FDIC insured up to $8M', 'No account fees', 'Autopilot features'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '4.00% APY',
    tags: ['high-yield', 'fintech', 'high-fdic'],
    affiliateUrl: '#',
    issuerIcon: 'TrendingUp',
    cardColor: 'from-indigo-600 via-indigo-500 to-blue-600',
    rating: 4.6,
  },
  {
    id: 'betterment-cash',
    name: 'Betterment Cash Reserve',
    category: 'banking',
    subcategory: 'Cash Management',
    description: 'High-yield cash account with up to $2M FDIC insurance through partner banks',
    features: ['4.00% APY', 'Up to $2M FDIC coverage', 'No minimum balance', 'Seamless investing integration'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 90,
    apr: '4.00% APY',
    tags: ['high-yield', 'fintech', 'investing'],
    affiliateUrl: '#',
    issuerIcon: 'Coins',
    cardColor: 'from-teal-600 via-teal-500 to-emerald-600',
    rating: 4.5,
  },
  {
    id: 'ufb-direct-savings',
    name: 'UFB Direct High-Yield Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Among the highest APYs available with no minimum balance requirement',
    features: ['4.31% APY', 'No minimum balance', 'No monthly fees', 'Mobile check deposit'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 85,
    apr: '4.31% APY',
    tags: ['high-yield', 'top-apy', 'no-fee'],
    affiliateUrl: '#',
    issuerIcon: 'DollarSign',
    cardColor: 'from-green-600 via-green-500 to-emerald-600',
    rating: 4.4,
  },
  {
    id: 'bread-savings',
    name: 'Bread Savings High-Yield',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'Competitive rates with flexible savings and CD options',
    features: ['4.15% APY', 'Low $100 minimum deposit', 'No monthly fees', 'Multiple CD terms'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 70,
    apr: '4.15% APY',
    tags: ['high-yield', 'low-minimum', 'cds'],
    affiliateUrl: '#',
    issuerIcon: 'Wallet',
    cardColor: 'from-amber-600 via-amber-500 to-yellow-600',
    rating: 4.3,
  },
  {
    id: 'varo-savings',
    name: 'Varo Bank Savings Account',
    category: 'banking',
    subcategory: 'Fintech Banks',
    description: 'Mobile-first banking with up to 5% APY on savings with qualifying direct deposits',
    features: ['Up to 5.00% APY', 'No monthly fees', 'Early direct deposit', 'Save Your Pay feature'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 60,
    apr: 'Up to 5.00% APY',
    tags: ['high-yield', 'fintech', 'mobile-first'],
    affiliateUrl: '#',
    issuerIcon: 'Smartphone',
    cardColor: 'from-lime-600 via-lime-500 to-green-600',
    rating: 4.2,
  },
  {
    id: 'lemonade-renters',
    name: 'Lemonade Renters Insurance',
    category: 'insurance',
    subcategory: 'Renters Insurance',
    description: 'Instant AI-powered renters insurance starting at $5/month',
    features: ['Instant quotes', 'AI-powered claims', 'Starting at $5/month', 'Giveback program'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 25,
    tags: ['renters', 'cheap', 'instant'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'progressive-auto',
    name: 'Progressive Auto Insurance',
    category: 'insurance',
    subcategory: 'Auto Insurance',
    description: 'Name your price tool to find coverage that fits your budget',
    features: ['Name Your Price tool', 'Snapshot discount', 'Bundle savings', '24/7 customer service'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    tags: ['auto', 'customizable', 'discounts'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'robinhood',
    name: 'Robinhood',
    category: 'investing',
    subcategory: 'Stock Trading Apps',
    description: 'Commission-free stock, ETF, options, and crypto trading',
    features: ['Commission-free trades', 'Fractional shares', 'Easy-to-use app', 'Crypto trading'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['stocks', 'crypto', 'free-trading'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'betterment',
    name: 'Betterment',
    category: 'investing',
    subcategory: 'Robo-Advisors',
    description: 'Automated investing with tax-efficient strategies',
    features: ['Automated portfolio management', 'Tax-loss harvesting', 'Goal-based investing', 'Low 0.25% fee'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    tags: ['robo-advisor', 'automated', 'tax-efficient'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'self-credit-builder',
    name: 'Self Credit Builder',
    category: 'credit-builder',
    subcategory: 'Credit Builder Loans',
    description: 'Build credit while you save with a credit-builder loan',
    features: ['Reports to all 3 bureaus', 'Build savings while building credit', 'No credit check to apply', 'Starting at $25/month'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 40,
    tags: ['credit-builder', 'savings', 'no-credit-check'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'boom-rent-reporting',
    name: 'Boom Pay',
    category: 'credit-builder',
    subcategory: 'Rent Reporting',
    description: 'Report your rent payments to all 3 credit bureaus',
    features: ['Reports to all 3 bureaus', 'Report past 24 months of rent', 'Average 25 point score increase', 'Simple setup'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 30,
    tags: ['rent-reporting', 'credit-builder', 'easy'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'turbotax-free',
    name: 'TurboTax Free Edition',
    category: 'tax-tools',
    subcategory: 'Free Tax Filing',
    description: 'Free federal and state filing for simple tax returns',
    features: ['Free federal filing', 'Free state filing', 'Simple returns only', 'Step-by-step guidance'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 15,
    tags: ['free', 'tax-filing', 'simple'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'identityguard',
    name: 'Identity Guard',
    category: 'identity-security',
    subcategory: 'Identity Protection',
    description: 'AI-powered identity theft protection and monitoring',
    features: ['Dark web monitoring', 'Social media monitoring', '$1M insurance', 'AI-powered alerts'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['identity-protection', 'monitoring', 'ai-powered'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'ynab',
    name: 'YNAB (You Need A Budget)',
    category: 'budgeting-apps',
    subcategory: 'Budgeting Apps',
    description: 'Zero-based budgeting app that helps you break the paycheck-to-paycheck cycle',
    features: ['Zero-based budgeting', 'Bank sync', 'Goal tracking', '34-day free trial'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    tags: ['budgeting', 'zero-based', 'goals'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'rakuten',
    name: 'Rakuten',
    category: 'rewards-cashback',
    subcategory: 'Cashback Apps',
    description: 'Get cash back when you shop at 3,500+ stores',
    features: ['Up to 40% cash back', '$10 signup bonus', 'Browser extension', 'In-store offers'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 30,
    signupBonus: '$10 welcome bonus',
    tags: ['cashback', 'shopping', 'browser-extension'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'sofi-student-refi',
    name: 'SoFi Student Loan Refinancing',
    category: 'student-finance',
    subcategory: 'Student Loan Refinancing',
    description: 'Lower your student loan rate with no fees',
    features: ['No origination fees', 'Unemployment protection', 'Rate discount with autopay', 'Career coaching'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 45000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 200,
    apr: '4.49% - 9.99%',
    tags: ['student-loans', 'refinancing', 'no-fees'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'earnest-student-loan',
    name: 'Earnest Student Loans',
    category: 'student-finance',
    subcategory: 'Private Student Loans',
    description: 'Private student loans with flexible repayment options',
    features: ['Skip a payment once a year', 'Precision pricing', 'No fees', 'Choose your payment date'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 35000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 150,
    apr: '4.29% - 14.99%',
    tags: ['student-loans', 'private', 'flexible'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'experian-credit-monitor',
    name: 'Experian CreditWorks',
    category: 'identity-security',
    subcategory: 'Credit Monitoring',
    description: 'Real-time credit monitoring and alerts from Experian',
    features: ['FICO Score tracking', 'Real-time alerts', 'Dark web surveillance', 'Identity theft insurance'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 40,
    tags: ['credit-monitoring', 'experian', 'alerts'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    category: 'identity-security',
    subcategory: 'VPN Services',
    description: 'Secure VPN service with advanced privacy features',
    features: ['5,500+ servers worldwide', 'Double VPN encryption', 'No-log policy', 'Threat Protection'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 30,
    tags: ['vpn', 'privacy', 'security'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'rocket-money',
    name: 'Rocket Money',
    category: 'budgeting-apps',
    subcategory: 'Bill Negotiation',
    description: 'Cancel subscriptions and lower bills automatically',
    features: ['Cancel unwanted subscriptions', 'Negotiate lower bills', 'Track spending', 'Smart savings'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 25,
    tags: ['bill-negotiation', 'subscriptions', 'savings'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'acorns',
    name: 'Acorns',
    category: 'budgeting-apps',
    subcategory: 'Round-Up Savings',
    description: 'Invest your spare change automatically',
    features: ['Round-up investments', 'Found Money rewards', 'IRA accounts', 'Smart portfolio'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    tags: ['investing', 'round-up', 'automated'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'swagbucks',
    name: 'Swagbucks',
    category: 'rewards-cashback',
    subcategory: 'Survey Earnings',
    description: 'Earn rewards for surveys, watching videos, and shopping',
    features: ['$10 signup bonus', 'Multiple earning methods', 'PayPal cashout', 'Gift card options'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 15,
    signupBonus: '$10 welcome bonus',
    tags: ['surveys', 'rewards', 'cashback'],
    affiliateUrl: '#',
    rating: 4.2,
  },
  {
    id: 'drop-rewards',
    name: 'Drop Rewards',
    category: 'rewards-cashback',
    subcategory: 'Rewards Programs',
    description: 'Earn points for shopping at your favorite brands',
    features: ['Link any card', 'Automatic rewards', 'No receipts needed', 'Redeem for gift cards'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 10,
    tags: ['rewards', 'automatic', 'gift-cards'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'hrblock-tax',
    name: 'H&R Block Tax',
    category: 'tax-tools',
    subcategory: 'Paid Tax Filing',
    description: 'Expert tax preparation with in-person and online options',
    features: ['Expert review included', 'Max refund guarantee', 'Audit support', 'Year-round help'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 25,
    tags: ['tax-filing', 'expert', 'audit-support'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'cashapp-tax',
    name: 'Cash App Taxes',
    category: 'tax-tools',
    subcategory: 'Free Tax Filing',
    description: 'Completely free tax filing with no hidden fees',
    features: ['100% free filing', 'All forms supported', 'Fast refunds', 'Max refund guarantee'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 10,
    tags: ['free', 'tax-filing', 'fast'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'fundbox-loc',
    name: 'Fundbox Line of Credit',
    category: 'business-funding',
    subcategory: 'Business Line of Credit',
    description: 'Fast, flexible business credit with no impact on personal credit',
    features: ['Up to $150,000', 'No personal credit impact', 'Weekly repayments', 'Draw funds anytime'],
    creditMin: 600,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '4.66% - 8.99%',
    tags: ['business', 'flexible', 'fast'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'kabbage-mca',
    name: 'Kabbage Funding',
    category: 'business-funding',
    subcategory: 'Merchant Cash Advance',
    description: 'Fast business funding with automated repayments',
    features: ['Same-day funding', 'Automated daily payments', 'Up to $250,000', 'No collateral'],
    creditMin: 550,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 250,
    apr: '24% - 99%',
    tags: ['mca', 'fast-funding', 'automated'],
    affiliateUrl: '#',
    rating: 4.1,
  },
  {
    id: 'geico-auto',
    name: 'GEICO Auto Insurance',
    category: 'insurance',
    subcategory: 'Auto Insurance',
    description: '15 minutes could save you 15% or more on car insurance',
    features: ['24/7 customer service', 'Easy online quotes', 'Multi-policy discounts', 'Mobile app'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['auto', 'discounts', 'fast-quotes'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'policygenius-life',
    name: 'Policygenius Life Insurance',
    category: 'insurance',
    subcategory: 'Life Insurance',
    description: 'Compare life insurance quotes from top carriers',
    features: ['Compare 30+ companies', 'No-exam options', 'Free quotes', 'Licensed advisors'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    tags: ['life', 'comparison', 'no-exam'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'webull-trading',
    name: 'Webull',
    category: 'investing',
    subcategory: 'Stock Trading Apps',
    description: 'Commission-free trading with advanced charting tools',
    features: ['Free stocks on signup', 'Extended hours trading', 'Advanced charts', 'Paper trading'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    signupBonus: 'Up to 12 free stocks',
    tags: ['stocks', 'free-trading', 'advanced'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'fundrise-real-estate',
    name: 'Fundrise',
    category: 'investing',
    subcategory: 'Real Estate Investing',
    description: 'Invest in private real estate with just $10',
    features: ['$10 minimum', 'Diversified portfolios', 'Historical 10%+ returns', 'Low fees'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['real-estate', 'low-minimum', 'passive'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'capital-one-secured',
    name: 'Capital One Platinum Secured',
    category: 'credit-builder',
    subcategory: 'Secured Cards',
    description: 'Build credit with a secured card and automatic credit line reviews',
    features: ['$200 minimum deposit', 'Automatic credit line reviews', 'CreditWise monitoring', 'No annual fee'],
    creditMin: 300,
    creditMax: 650,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 40,
    apr: '30.74%',
    annualFee: '$0',
    tags: ['secured', 'no-fee', 'credit-builder'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'ally-savings',
    name: 'Ally High-Yield Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'No minimum balance, no monthly fees, competitive APY',
    features: ['4.25% APY', 'No minimum balance', 'No monthly fees', 'Buckets for saving goals'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '4.25% APY',
    tags: ['high-yield', 'no-fee', 'online'],
    affiliateUrl: '#',
    issuerIcon: 'PiggyBank',
    cardColor: 'from-purple-700 via-purple-600 to-violet-700',
    rating: 4.7,
  },
  // Estate Planning Tools
  {
    id: 'trust-and-will',
    name: 'Trust & Will',
    category: 'estate-planning',
    subcategory: 'Living Trusts',
    description: 'Create a complete estate plan online in minutes - wills, trusts, and more',
    features: ['Living trusts from $599', 'State-specific documents', 'Attorney-reviewed', 'Digital vault storage'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['trusts', 'wills', 'estate-planning', 'online'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'fabric-life',
    name: 'Fabric',
    category: 'estate-planning',
    subcategory: 'Online Wills',
    description: 'Free will plus affordable life insurance designed for families',
    features: ['Free will creation', 'Life insurance from $5/month', '10-minute application', 'Family-focused'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 35,
    tags: ['free-will', 'life-insurance', 'families'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'legalzoom-will',
    name: 'LegalZoom Wills',
    category: 'estate-planning',
    subcategory: 'Legal Document Services',
    description: 'Create a legally binding will with attorney support',
    features: ['Attorney review available', 'State-specific forms', 'Living will included', 'Revisions anytime'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 40,
    tags: ['wills', 'legal', 'attorney-backed'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  // Renters Insurance (Super Converters)
  {
    id: 'policygenius-renters',
    name: 'Policygenius Renters',
    category: 'renters-insurance',
    subcategory: 'Traditional Carriers',
    description: 'Compare renters insurance quotes from top carriers in minutes',
    features: ['Compare 30+ carriers', 'Average $15/month', 'No-obligation quotes', 'Licensed advisors'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 30,
    tags: ['renters', 'comparison', 'cheap'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'lemonade-renters-v2',
    name: 'Lemonade Renters',
    category: 'renters-insurance',
    subcategory: 'AI-Powered Insurance',
    description: 'AI-powered renters insurance starting at $5/month with instant claims',
    features: ['Starting at $5/month', 'Instant AI claims', '90-second signup', 'Giveback program'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 25,
    tags: ['renters', 'cheap', 'instant', 'ai-powered'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'allstate-renters',
    name: 'Allstate Renters',
    category: 'renters-insurance',
    subcategory: 'Traditional Carriers',
    description: 'Trusted renters coverage with bundle discounts and 24/7 support',
    features: ['Bundle with auto for savings', 'Identity restoration', '24/7 claims', 'Easy online quotes'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 35,
    tags: ['renters', 'bundle', 'trusted-brand'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  // Cashback Apps (Insane Conversion)
  {
    id: 'honey-shopping',
    name: 'Honey by PayPal',
    category: 'rewards-cashback',
    subcategory: 'Browser Extensions',
    description: 'Free browser extension that finds and applies coupon codes automatically',
    features: ['Automatic coupon codes', 'Price tracking alerts', 'PayPal cashback', 'Works on 30K+ sites'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 15,
    signupBonus: 'Free to use',
    tags: ['free', 'coupons', 'browser-extension', 'automatic'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'capital-one-shopping',
    name: 'Capital One Shopping',
    category: 'rewards-cashback',
    subcategory: 'Browser Extensions',
    description: 'Free browser tool that finds lower prices and earns rewards automatically',
    features: ['Price comparison', 'Automatic coupons', 'Gift card rewards', 'No Capital One card needed'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 10,
    signupBonus: 'Free rewards',
    tags: ['free', 'price-comparison', 'rewards'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'upside-gas',
    name: 'Upside',
    category: 'rewards-cashback',
    subcategory: 'Gas Cashback',
    description: 'Earn up to 25¢/gallon cashback on gas, plus grocery and restaurant rewards',
    features: ['Up to 25¢/gallon gas cashback', 'Grocery cashback', 'Restaurant rewards', 'Cash out to PayPal'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    signupBonus: 'Up to 25¢/gal bonus',
    tags: ['gas', 'cashback', 'groceries', 'free'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  // Credit Builder Apps (Massive Conversion)
  {
    id: 'kikoff-credit',
    name: 'Kikoff',
    category: 'credit-builder',
    subcategory: 'Credit Builder Loans',
    description: 'Build credit for just $5/month with no credit check required',
    features: ['Only $5/month', 'No credit check', 'Reports to all 3 bureaus', 'Build credit history'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 25,
    tags: ['credit-builder', 'cheap', 'no-credit-check'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'chime-credit-builder',
    name: 'Chime Credit Builder',
    category: 'credit-builder',
    subcategory: 'Credit Builder Cards',
    description: 'Build credit with no annual fee, no interest, and no credit check',
    features: ['No credit check', 'No annual fee', 'No interest', 'Reports to all 3 bureaus'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 35,
    annualFee: '$0',
    tags: ['credit-builder', 'no-fee', 'no-interest', 'secured'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  // Micro-Investing Apps (Start with $1-$5)
  {
    id: 'acorns-invest',
    name: 'Acorns',
    category: 'micro-investing',
    subcategory: 'Round-Up Apps',
    description: 'Invest spare change automatically - start with just $5',
    features: ['Round-up investments', 'Start with $5', 'Found Money partners', 'IRA accounts available'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    signupBonus: '$20 bonus with deposit',
    tags: ['round-up', 'beginner', 'automated', 'micro-investing'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'stash-invest',
    name: 'Stash',
    category: 'micro-investing',
    subcategory: 'Beginner Platforms',
    description: 'Start investing with just $1 - perfect for beginners',
    features: ['Start with $1', 'Fractional shares', 'Banking + investing', 'Stock-Back rewards'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 30,
    signupBonus: '$5 bonus',
    tags: ['beginner', 'fractional', 'micro-investing'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'webull-micro',
    name: 'Webull',
    category: 'micro-investing',
    subcategory: 'Free Stock Offers',
    description: 'Get up to 12 free stocks when you sign up - commission-free trading',
    features: ['Up to 12 free stocks', 'Commission-free', 'Fractional shares', 'Extended hours trading'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    signupBonus: 'Up to 12 free stocks',
    tags: ['free-stocks', 'commission-free', 'trading'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  // Budgeting / Subscription Tracker Apps
  {
    id: 'truebill-budget',
    name: 'Truebill (Rocket Money)',
    category: 'budgeting-apps',
    subcategory: 'Subscription Managers',
    description: 'Find and cancel unwanted subscriptions - save money instantly',
    features: ['Cancel subscriptions', 'Lower bills', 'Track spending', 'Premium negotiation'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 25,
    tags: ['subscriptions', 'bill-negotiation', 'savings'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'digit-savings',
    name: 'Digit',
    category: 'budgeting-apps',
    subcategory: 'Round-Up Savings',
    description: 'AI analyzes your spending and saves money automatically',
    features: ['Automatic savings', 'Overdraft protection', 'Multiple savings goals', 'No minimum balance'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    tags: ['automatic', 'ai-savings', 'goals'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  // Refinancing Offers
  {
    id: 'sofi-refi-mortgage',
    name: 'SoFi Mortgage Refinance',
    category: 'refinancing',
    subcategory: 'Mortgage Refinance',
    description: 'No hidden fees, competitive rates, and a fully online application process',
    features: ['No origination fees', 'Rate lock protection', 'Online application', 'Member benefits'],
    creditMin: 680,
    creditMax: 850,
    incomeMin: 50000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 500,
    apr: '6.125% - 7.250%',
    tags: ['mortgage', 'no-fees', 'online'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'better-mortgage-refi',
    name: 'Better Mortgage',
    category: 'refinancing',
    subcategory: 'Mortgage Refinance',
    description: 'Digital-first refinancing with instant rate quotes and no commission',
    features: ['No commission', '3-minute pre-approval', 'Rate lock', 'Digital closing'],
    creditMin: 620,
    creditMax: 850,
    incomeMin: 40000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 400,
    apr: '6.250% - 7.500%',
    tags: ['mortgage', 'digital', 'fast'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'rocket-mortgage-refi',
    name: 'Rocket Mortgage Refinance',
    category: 'refinancing',
    subcategory: 'Mortgage Refinance',
    description: 'America\'s largest mortgage lender with award-winning technology',
    features: ['Verified approval in minutes', 'Rate shield', 'Home Loan Experts', 'RateShield Approval'],
    creditMin: 620,
    creditMax: 850,
    incomeMin: 45000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 450,
    apr: '6.375% - 7.625%',
    tags: ['mortgage', 'trusted', 'technology'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'lending-tree-auto',
    name: 'LendingTree Auto Refinance',
    category: 'refinancing',
    subcategory: 'Auto Loan Refinance',
    description: 'Compare multiple auto refinance offers in minutes',
    features: ['Compare up to 5 lenders', 'Soft credit check', 'Same-day decisions', 'Save up to $100/month'],
    creditMin: 580,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 150,
    apr: '5.99% - 18.99%',
    tags: ['auto', 'comparison', 'soft-pull'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'caribou-auto-refi',
    name: 'Caribou Auto Refinance',
    category: 'refinancing',
    subcategory: 'Auto Loan Refinance',
    description: 'AI-powered auto refinance that finds you the best rate instantly',
    features: ['AI rate matching', 'No impact to credit score', '2-minute application', 'Average $115/mo savings'],
    creditMin: 550,
    creditMax: 850,
    incomeMin: 20000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 175,
    apr: '4.99% - 17.99%',
    tags: ['auto', 'ai-powered', 'quick'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'refijet-auto',
    name: 'RefiJet',
    category: 'refinancing',
    subcategory: 'Auto Loan Refinance',
    description: 'Specialized auto refinancing with competitive rates for all credit types',
    features: ['All credit types welcome', 'Fast approval', 'No prepayment penalty', 'Direct-to-lender'],
    creditMin: 500,
    creditMax: 850,
    incomeMin: 18000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 125,
    apr: '5.49% - 21.99%',
    tags: ['auto', 'bad-credit', 'accessible'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'sofi-student-refi',
    name: 'SoFi Student Loan Refinance',
    category: 'refinancing',
    subcategory: 'Student Loan Refinance',
    description: 'Refinance federal and private student loans with no fees',
    features: ['No origination fees', 'Unemployment protection', 'Rate discount with autopay', 'Member benefits'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 30000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '4.99% - 9.99%',
    tags: ['student', 'no-fees', 'protection'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'earnest-student-refi',
    name: 'Earnest Student Loan Refinance',
    category: 'refinancing',
    subcategory: 'Student Loan Refinance',
    description: 'Customize your student loan refinance with flexible payment options',
    features: ['Choose your payment date', 'Skip a payment option', 'No fees', 'Precision pricing'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 35000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 175,
    apr: '5.19% - 9.74%',
    tags: ['student', 'flexible', 'no-fees'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'credible-student-refi',
    name: 'Credible Student Refinance',
    category: 'refinancing',
    subcategory: 'Student Loan Refinance',
    description: 'Compare personalized rates from top lenders without affecting credit',
    features: ['Compare 10+ lenders', 'No credit impact', 'Real rates in 2 minutes', 'Concierge support'],
    creditMin: 620,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 150,
    apr: '5.09% - 10.49%',
    tags: ['student', 'comparison', 'soft-pull'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'upgrade-personal-refi',
    name: 'Upgrade Personal Loan Refinance',
    category: 'refinancing',
    subcategory: 'Personal Loan Refinance',
    description: 'Consolidate and refinance personal loans with fixed rates',
    features: ['Fixed rates', 'No prepayment fees', 'Same-day funding available', 'Credit monitoring'],
    creditMin: 580,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '8.49% - 35.99%',
    tags: ['personal', 'fixed-rate', 'fast'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'sofi-personal-refi',
    name: 'SoFi Personal Loan Refinance',
    category: 'refinancing',
    subcategory: 'Personal Loan Refinance',
    description: 'Refinance high-interest debt with competitive fixed rates',
    features: ['No fees', 'Unemployment protection', 'Member perks', 'Fixed payments'],
    creditMin: 680,
    creditMax: 850,
    incomeMin: 40000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 150,
    apr: '8.99% - 25.81%',
    tags: ['personal', 'no-fees', 'member-benefits'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'figure-heloc-cashout',
    name: 'Figure Cash-Out Refinance',
    category: 'refinancing',
    subcategory: 'Cash-Out Refinance',
    description: 'Unlock your home equity with a fast, online cash-out refinance',
    features: ['Funding in 5 days', '100% online process', 'Fixed rates available', 'No hidden fees'],
    creditMin: 640,
    creditMax: 850,
    incomeMin: 50000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 350,
    apr: '6.99% - 15.99%',
    tags: ['cash-out', 'heloc', 'fast'],
    affiliateUrl: '#',
    rating: 4.5,
  },
];

export function getOffersByCategory(categoryId: string): ProductOffer[] {
  return SAMPLE_OFFERS.filter(offer => offer.category === categoryId);
}

export function getOffersBySubcategory(categoryId: string, subcategory: string): ProductOffer[] {
  return SAMPLE_OFFERS.filter(
    offer => offer.category === categoryId && offer.subcategory === subcategory
  );
}

export function calculateMatchScore(offer: ProductOffer): number {
  let score = 70;
  if (offer.rating >= 4.5) score += 10;
  else if (offer.rating >= 4.0) score += 5;
  if (offer.annualFee === '$0') score += 5;
  if (offer.signupBonus) score += 5;
  if (offer.studentFriendly) score += 3;
  if (offer.creditMin <= 600) score += 2;
  return Math.min(score, 98);
}

export function getMatchExplanation(offer: ProductOffer, score: number): string {
  const reasons: string[] = [];
  
  if (offer.rating >= 4.5) reasons.push('highly rated by users');
  if (offer.annualFee === '$0') reasons.push('no annual fee');
  if (offer.signupBonus) reasons.push('has signup bonus');
  if (offer.creditMin <= 600) reasons.push('accessible credit requirements');
  if (offer.studentFriendly) reasons.push('student-friendly');
  
  if (score >= 90) {
    return `Excellent match: ${reasons.slice(0, 2).join(', ')}. High approval odds for most profiles.`;
  } else if (score >= 80) {
    return `Strong match: ${reasons.slice(0, 2).join(', ')}. Good fit for typical applicants.`;
  } else {
    return `Suitable option: ${reasons[0] || 'standard terms'}. Review requirements before applying.`;
  }
}
