export interface ProductOffer {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  features: string[];
  creditMin: number;
  creditMax: number;
  incomeMin: number;
  studentFriendly: boolean;
  businessOwnerFriendly: boolean;
  payout: number;
  apr?: string;
  annualFee?: string;
  signupBonus?: string;
  tags: string[];
  affiliateUrl: string;
  logoUrl?: string;
  rating: number;
}

export const CATEGORIES = {
  PRIMARY: [
    { id: 'credit-cards', name: 'Credit Cards', icon: 'CreditCard', description: 'AI-matched cards based on your profile and goals' },
    { id: 'personal-loans', name: 'Personal Loans', icon: 'Wallet', description: 'Compare lenders for consolidation and lower APRs' },
    { id: 'business-funding', name: 'Business Funding', icon: 'Building2', description: 'Business cards, lines of credit, and startup capital' },
    { id: 'banking', name: 'Banking', icon: 'Landmark', description: 'High-yield savings, checking, and cash tools' },
    { id: 'insurance', name: 'Insurance', icon: 'Shield', description: 'Auto, home, and life insurance quotes' },
    { id: 'investing', name: 'Investing', icon: 'TrendingUp', description: 'Brokerages, robo-advisors, and long-term tools' },
  ],
  SECONDARY: [
    { id: 'credit-builder', name: 'Credit Builder', icon: 'Target', description: 'Build or rebuild your credit score' },
    { id: 'student-finance', name: 'Student Finance', icon: 'GraduationCap', description: 'Student loans, refinancing, and banking' },
  ],
  SUPPORTING: [
    { id: 'tax-tools', name: 'Tax Tools', icon: 'Calculator', description: 'Free and paid tax filing solutions' },
    { id: 'identity-security', name: 'Identity & Security', icon: 'Lock', description: 'Identity protection and credit monitoring' },
    { id: 'budgeting-apps', name: 'Budgeting Apps', icon: 'PieChart', description: 'Budgeting, automation, and money management' },
    { id: 'rewards-cashback', name: 'Rewards & Cashback', icon: 'Gift', description: 'Cashback apps, surveys, and rewards platforms' },
  ],
  FLAGSHIP: [
    { id: 'real-estate', name: 'Real Estate Concierge', icon: 'Home', description: 'Our flagship luxury real estate + RBO system' },
  ],
} as const;

export const SUBCATEGORIES: Record<string, string[]> = {
  'credit-cards': [
    'Best Card Picks',
    'Cash Back Cards',
    'Travel & Points Cards',
    '0% APR Cards',
    'Student Cards',
    'Secured Cards',
    'Business Credit Cards',
    'Credit Builder Cards',
    'No Credit Check Cards',
  ],
  'personal-loans': [
    'Debt Consolidation',
    'Bad Credit Loans',
    'Emergency Loans',
    'Installment Loans',
    'Soft-Pull Pre-Qualification',
    'Student Loan Refinancing',
    'Medical/Dental Financing',
  ],
  'business-funding': [
    'Merchant Cash Advance',
    'Business Line of Credit',
    'Business Term Loans',
    'Startup Capital',
    'Equipment Financing',
    'Invoice Factoring',
    'Revenue-Based Financing',
    'E-Commerce Seller Funding',
  ],
  'banking': [
    'High-Yield Savings',
    'Checking Accounts',
    'Fintech Banks',
    'Debit Cards',
    'Cash Management Accounts',
    'Business Banking',
    'Teen/Student Banking',
  ],
  'insurance': [
    'Auto Insurance',
    'Home Insurance',
    'Renters Insurance',
    'Life Insurance',
    'Health Insurance',
    'Pet Insurance',
    'Business Insurance',
    'Travel Insurance',
  ],
  'investing': [
    'Stock Trading Apps',
    'Robo-Advisors',
    'Long-Term Investing',
    'Crypto Platforms',
    'IRA/Roth IRA',
    'Real Estate Investing',
    'Micro-Investment Apps',
  ],
  'credit-builder': [
    'Secured Cards',
    'Credit Builder Cards',
    'Credit Builder Loans',
    'Rent Reporting',
    'Utility Reporting',
    'Subscription Builders',
  ],
  'student-finance': [
    'Student Loan Refinancing',
    'Private Student Loans',
    'Tuition Financing',
    'FAFSA Assistance',
    'Scholarship Matching',
    'Student Banking',
    'Student Credit Cards',
  ],
  'tax-tools': [
    'Free Tax Filing',
    'Paid Tax Filing',
    'Pro-Assisted Filing',
    'Tax Refund Advance',
  ],
  'identity-security': [
    'Identity Protection',
    'Credit Monitoring',
    'Password Managers',
    'VPN Services',
  ],
  'budgeting-apps': [
    'Budgeting Apps',
    'Bill Negotiation',
    'Subscription Managers',
    'Cash Back Apps',
    'Round-Up Savings',
  ],
  'rewards-cashback': [
    'Cashback Apps',
    'Mystery Shopping',
    'Rewards Programs',
    'Gift Card Offers',
    'Survey Earnings',
  ],
  'real-estate': [
    'Reverse Buyer Origination',
    'Home Buyer Tools',
    'Luxury Concierge',
    'Market Discovery',
    'Pre-Approval Guidance',
  ],
};

export const SAMPLE_OFFERS: ProductOffer[] = [
  {
    id: 'chase-sapphire-preferred',
    name: 'Chase Sapphire Preferred',
    category: 'credit-cards',
    subcategory: 'Travel & Points Cards',
    description: 'Premium travel rewards card with flexible point redemption and travel protections',
    features: ['60,000 bonus points after $4,000 spend', '2X points on travel and dining', 'No foreign transaction fees', 'Trip cancellation insurance'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 40000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '21.49% - 28.49%',
    annualFee: '$95',
    signupBonus: '60,000 points ($750 value)',
    tags: ['travel', 'points', 'premium'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'citi-double-cash',
    name: 'Citi Double Cash Card',
    category: 'credit-cards',
    subcategory: 'Cash Back Cards',
    description: 'Earn 2% cash back on every purchase - 1% when you buy, 1% when you pay',
    features: ['2% cash back on all purchases', 'No annual fee', 'No category restrictions', '0% intro APR for 18 months'],
    creditMin: 670,
    creditMax: 850,
    incomeMin: 25000,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '18.49% - 28.49%',
    annualFee: '$0',
    signupBonus: 'None',
    tags: ['cashback', 'no-fee', 'simple'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'discover-it-secured',
    name: 'Discover it Secured',
    category: 'credit-cards',
    subcategory: 'Secured Cards',
    description: 'Build credit with a secured card that matches your cash back at the end of year one',
    features: ['2% cash back at restaurants and gas stations', 'Cashback match first year', 'No annual fee', 'Free FICO score'],
    creditMin: 300,
    creditMax: 650,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 50,
    apr: '28.24%',
    annualFee: '$0',
    signupBonus: 'Cashback Match',
    tags: ['secured', 'credit-builder', 'no-fee'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'sofi-personal-loan',
    name: 'SoFi Personal Loan',
    category: 'personal-loans',
    subcategory: 'Debt Consolidation',
    description: 'Low-rate personal loans with no fees and unemployment protection',
    features: ['No origination fees', 'No prepayment penalties', 'Unemployment protection', 'Rate discount with autopay'],
    creditMin: 680,
    creditMax: 850,
    incomeMin: 45000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 150,
    apr: '8.99% - 25.81%',
    tags: ['low-rate', 'no-fees', 'debt-consolidation'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'upstart-personal-loan',
    name: 'Upstart Personal Loan',
    category: 'personal-loans',
    subcategory: 'Bad Credit Loans',
    description: 'AI-powered lending that looks beyond credit score',
    features: ['Consider education and employment', 'Fast funding', 'Fixed rates', 'Accepts lower credit scores'],
    creditMin: 580,
    creditMax: 850,
    incomeMin: 20000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 100,
    apr: '7.80% - 35.99%',
    tags: ['bad-credit', 'ai-powered', 'fast-funding'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'bluevine-loc',
    name: 'BlueVine Business Line of Credit',
    category: 'business-funding',
    subcategory: 'Business Line of Credit',
    description: 'Flexible business financing with fast approval and competitive rates',
    features: ['Up to $250,000 credit line', 'Draw funds as needed', 'Only pay for what you use', 'Fast online application'],
    creditMin: 625,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 300,
    apr: '7.80% - 25.00%',
    tags: ['business', 'line-of-credit', 'flexible'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'ondeck-term-loan',
    name: 'OnDeck Business Term Loan',
    category: 'business-funding',
    subcategory: 'Business Term Loans',
    description: 'Fast business loans with same-day funding available',
    features: ['$5K to $250K loans', 'Same-day funding possible', 'Fixed daily/weekly payments', 'Build business credit'],
    creditMin: 600,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 250,
    apr: '29.9% - 97.3%',
    tags: ['business', 'fast-funding', 'term-loan'],
    affiliateUrl: '#',
    rating: 4.2,
  },
  {
    id: 'chime-checking',
    name: 'Chime Checking Account',
    category: 'banking',
    subcategory: 'Fintech Banks',
    description: 'Fee-free online checking with early direct deposit and overdraft protection',
    features: ['No monthly fees', 'Get paid early', 'SpotMe overdraft up to $200', '60,000+ fee-free ATMs'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 80,
    tags: ['no-fee', 'fintech', 'early-deposit'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'sofi-savings',
    name: 'SoFi Checking & Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'High-yield savings with checking features and no account fees',
    features: ['4.50% APY on savings', 'No account fees', 'Early direct deposit', 'Fee-free overdraft'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 100,
    apr: '4.50% APY',
    tags: ['high-yield', 'no-fee', 'checking-savings'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'lemonade-renters',
    name: 'Lemonade Renters Insurance',
    category: 'insurance',
    subcategory: 'Renters Insurance',
    description: 'Instant AI-powered renters insurance starting at $5/month',
    features: ['Instant quotes', 'AI-powered claims', 'Starting at $5/month', 'Giveback program'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 25,
    tags: ['renters', 'cheap', 'instant'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'progressive-auto',
    name: 'Progressive Auto Insurance',
    category: 'insurance',
    subcategory: 'Auto Insurance',
    description: 'Name your price tool to find coverage that fits your budget',
    features: ['Name Your Price tool', 'Snapshot discount', 'Bundle savings', '24/7 customer service'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    tags: ['auto', 'customizable', 'discounts'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'robinhood',
    name: 'Robinhood',
    category: 'investing',
    subcategory: 'Stock Trading Apps',
    description: 'Commission-free stock, ETF, options, and crypto trading',
    features: ['Commission-free trades', 'Fractional shares', 'Easy-to-use app', 'Crypto trading'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['stocks', 'crypto', 'free-trading'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'betterment',
    name: 'Betterment',
    category: 'investing',
    subcategory: 'Robo-Advisors',
    description: 'Automated investing with tax-efficient strategies',
    features: ['Automated portfolio management', 'Tax-loss harvesting', 'Goal-based investing', 'Low 0.25% fee'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    tags: ['robo-advisor', 'automated', 'tax-efficient'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'self-credit-builder',
    name: 'Self Credit Builder',
    category: 'credit-builder',
    subcategory: 'Credit Builder Loans',
    description: 'Build credit while you save with a credit-builder loan',
    features: ['Reports to all 3 bureaus', 'Build savings while building credit', 'No credit check to apply', 'Starting at $25/month'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 40,
    tags: ['credit-builder', 'savings', 'no-credit-check'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'boom-rent-reporting',
    name: 'Boom Pay',
    category: 'credit-builder',
    subcategory: 'Rent Reporting',
    description: 'Report your rent payments to all 3 credit bureaus',
    features: ['Reports to all 3 bureaus', 'Report past 24 months of rent', 'Average 25 point score increase', 'Simple setup'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 30,
    tags: ['rent-reporting', 'credit-builder', 'easy'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'turbotax-free',
    name: 'TurboTax Free Edition',
    category: 'tax-tools',
    subcategory: 'Free Tax Filing',
    description: 'Free federal and state filing for simple tax returns',
    features: ['Free federal filing', 'Free state filing', 'Simple returns only', 'Step-by-step guidance'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 15,
    tags: ['free', 'tax-filing', 'simple'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'identityguard',
    name: 'Identity Guard',
    category: 'identity-security',
    subcategory: 'Identity Protection',
    description: 'AI-powered identity theft protection and monitoring',
    features: ['Dark web monitoring', 'Social media monitoring', '$1M insurance', 'AI-powered alerts'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['identity-protection', 'monitoring', 'ai-powered'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'ynab',
    name: 'YNAB (You Need A Budget)',
    category: 'budgeting-apps',
    subcategory: 'Budgeting Apps',
    description: 'Zero-based budgeting app that helps you break the paycheck-to-paycheck cycle',
    features: ['Zero-based budgeting', 'Bank sync', 'Goal tracking', '34-day free trial'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    tags: ['budgeting', 'zero-based', 'goals'],
    affiliateUrl: '#',
    rating: 4.8,
  },
  {
    id: 'rakuten',
    name: 'Rakuten',
    category: 'rewards-cashback',
    subcategory: 'Cashback Apps',
    description: 'Get cash back when you shop at 3,500+ stores',
    features: ['Up to 40% cash back', '$10 signup bonus', 'Browser extension', 'In-store offers'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 30,
    signupBonus: '$10 welcome bonus',
    tags: ['cashback', 'shopping', 'browser-extension'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'sofi-student-refi',
    name: 'SoFi Student Loan Refinancing',
    category: 'student-finance',
    subcategory: 'Student Loan Refinancing',
    description: 'Lower your student loan rate with no fees',
    features: ['No origination fees', 'Unemployment protection', 'Rate discount with autopay', 'Career coaching'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 45000,
    studentFriendly: false,
    businessOwnerFriendly: false,
    payout: 200,
    apr: '4.49% - 9.99%',
    tags: ['student-loans', 'refinancing', 'no-fees'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'earnest-student-loan',
    name: 'Earnest Student Loans',
    category: 'student-finance',
    subcategory: 'Private Student Loans',
    description: 'Private student loans with flexible repayment options',
    features: ['Skip a payment once a year', 'Precision pricing', 'No fees', 'Choose your payment date'],
    creditMin: 650,
    creditMax: 850,
    incomeMin: 35000,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 150,
    apr: '4.29% - 14.99%',
    tags: ['student-loans', 'private', 'flexible'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'experian-credit-monitor',
    name: 'Experian CreditWorks',
    category: 'identity-security',
    subcategory: 'Credit Monitoring',
    description: 'Real-time credit monitoring and alerts from Experian',
    features: ['FICO Score tracking', 'Real-time alerts', 'Dark web surveillance', 'Identity theft insurance'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 40,
    tags: ['credit-monitoring', 'experian', 'alerts'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    category: 'identity-security',
    subcategory: 'VPN Services',
    description: 'Secure VPN service with advanced privacy features',
    features: ['5,500+ servers worldwide', 'Double VPN encryption', 'No-log policy', 'Threat Protection'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 30,
    tags: ['vpn', 'privacy', 'security'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'rocket-money',
    name: 'Rocket Money',
    category: 'budgeting-apps',
    subcategory: 'Bill Negotiation',
    description: 'Cancel subscriptions and lower bills automatically',
    features: ['Cancel unwanted subscriptions', 'Negotiate lower bills', 'Track spending', 'Smart savings'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 25,
    tags: ['bill-negotiation', 'subscriptions', 'savings'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'acorns',
    name: 'Acorns',
    category: 'budgeting-apps',
    subcategory: 'Round-Up Savings',
    description: 'Invest your spare change automatically',
    features: ['Round-up investments', 'Found Money rewards', 'IRA accounts', 'Smart portfolio'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 20,
    tags: ['investing', 'round-up', 'automated'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'swagbucks',
    name: 'Swagbucks',
    category: 'rewards-cashback',
    subcategory: 'Survey Earnings',
    description: 'Earn rewards for surveys, watching videos, and shopping',
    features: ['$10 signup bonus', 'Multiple earning methods', 'PayPal cashout', 'Gift card options'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 15,
    signupBonus: '$10 welcome bonus',
    tags: ['surveys', 'rewards', 'cashback'],
    affiliateUrl: '#',
    rating: 4.2,
  },
  {
    id: 'drop-rewards',
    name: 'Drop Rewards',
    category: 'rewards-cashback',
    subcategory: 'Rewards Programs',
    description: 'Earn points for shopping at your favorite brands',
    features: ['Link any card', 'Automatic rewards', 'No receipts needed', 'Redeem for gift cards'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 10,
    tags: ['rewards', 'automatic', 'gift-cards'],
    affiliateUrl: '#',
    rating: 4.3,
  },
  {
    id: 'hrblock-tax',
    name: 'H&R Block Tax',
    category: 'tax-tools',
    subcategory: 'Paid Tax Filing',
    description: 'Expert tax preparation with in-person and online options',
    features: ['Expert review included', 'Max refund guarantee', 'Audit support', 'Year-round help'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 25,
    tags: ['tax-filing', 'expert', 'audit-support'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'cashapp-tax',
    name: 'Cash App Taxes',
    category: 'tax-tools',
    subcategory: 'Free Tax Filing',
    description: 'Completely free tax filing with no hidden fees',
    features: ['100% free filing', 'All forms supported', 'Fast refunds', 'Max refund guarantee'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 10,
    tags: ['free', 'tax-filing', 'fast'],
    affiliateUrl: '#',
    rating: 4.6,
  },
  {
    id: 'fundbox-loc',
    name: 'Fundbox Line of Credit',
    category: 'business-funding',
    subcategory: 'Business Line of Credit',
    description: 'Fast, flexible business credit with no impact on personal credit',
    features: ['Up to $150,000', 'No personal credit impact', 'Weekly repayments', 'Draw funds anytime'],
    creditMin: 600,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 200,
    apr: '4.66% - 8.99%',
    tags: ['business', 'flexible', 'fast'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'kabbage-mca',
    name: 'Kabbage Funding',
    category: 'business-funding',
    subcategory: 'Merchant Cash Advance',
    description: 'Fast business funding with automated repayments',
    features: ['Same-day funding', 'Automated daily payments', 'Up to $250,000', 'No collateral'],
    creditMin: 550,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 250,
    apr: '24% - 99%',
    tags: ['mca', 'fast-funding', 'automated'],
    affiliateUrl: '#',
    rating: 4.1,
  },
  {
    id: 'geico-auto',
    name: 'GEICO Auto Insurance',
    category: 'insurance',
    subcategory: 'Auto Insurance',
    description: '15 minutes could save you 15% or more on car insurance',
    features: ['24/7 customer service', 'Easy online quotes', 'Multi-policy discounts', 'Mobile app'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['auto', 'discounts', 'fast-quotes'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'policygenius-life',
    name: 'Policygenius Life Insurance',
    category: 'insurance',
    subcategory: 'Life Insurance',
    description: 'Compare life insurance quotes from top carriers',
    features: ['Compare 30+ companies', 'No-exam options', 'Free quotes', 'Licensed advisors'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: false,
    businessOwnerFriendly: true,
    payout: 100,
    tags: ['life', 'comparison', 'no-exam'],
    affiliateUrl: '#',
    rating: 4.7,
  },
  {
    id: 'webull-trading',
    name: 'Webull',
    category: 'investing',
    subcategory: 'Stock Trading Apps',
    description: 'Commission-free trading with advanced charting tools',
    features: ['Free stocks on signup', 'Extended hours trading', 'Advanced charts', 'Paper trading'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    signupBonus: 'Up to 12 free stocks',
    tags: ['stocks', 'free-trading', 'advanced'],
    affiliateUrl: '#',
    rating: 4.5,
  },
  {
    id: 'fundrise-real-estate',
    name: 'Fundrise',
    category: 'investing',
    subcategory: 'Real Estate Investing',
    description: 'Invest in private real estate with just $10',
    features: ['$10 minimum', 'Diversified portfolios', 'Historical 10%+ returns', 'Low fees'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 50,
    tags: ['real-estate', 'low-minimum', 'passive'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'capital-one-secured',
    name: 'Capital One Platinum Secured',
    category: 'credit-builder',
    subcategory: 'Secured Cards',
    description: 'Build credit with a secured card and automatic credit line reviews',
    features: ['$200 minimum deposit', 'Automatic credit line reviews', 'CreditWise monitoring', 'No annual fee'],
    creditMin: 300,
    creditMax: 650,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: false,
    payout: 40,
    apr: '30.74%',
    annualFee: '$0',
    tags: ['secured', 'no-fee', 'credit-builder'],
    affiliateUrl: '#',
    rating: 4.4,
  },
  {
    id: 'ally-savings',
    name: 'Ally High-Yield Savings',
    category: 'banking',
    subcategory: 'High-Yield Savings',
    description: 'No minimum balance, no monthly fees, competitive APY',
    features: ['4.25% APY', 'No minimum balance', 'No monthly fees', 'Buckets for saving goals'],
    creditMin: 0,
    creditMax: 850,
    incomeMin: 0,
    studentFriendly: true,
    businessOwnerFriendly: true,
    payout: 75,
    apr: '4.25% APY',
    tags: ['high-yield', 'no-fee', 'online'],
    affiliateUrl: '#',
    rating: 4.7,
  },
];

export function getOffersByCategory(categoryId: string): ProductOffer[] {
  return SAMPLE_OFFERS.filter(offer => offer.category === categoryId);
}

export function getOffersBySubcategory(categoryId: string, subcategory: string): ProductOffer[] {
  return SAMPLE_OFFERS.filter(
    offer => offer.category === categoryId && offer.subcategory === subcategory
  );
}

export function calculateMatchScore(offer: ProductOffer): number {
  let score = 70;
  if (offer.rating >= 4.5) score += 10;
  else if (offer.rating >= 4.0) score += 5;
  if (offer.annualFee === '$0') score += 5;
  if (offer.signupBonus) score += 5;
  if (offer.studentFriendly) score += 3;
  if (offer.creditMin <= 600) score += 2;
  return Math.min(score, 98);
}

export function getMatchExplanation(offer: ProductOffer, score: number): string {
  const reasons: string[] = [];
  
  if (offer.rating >= 4.5) reasons.push('highly rated by users');
  if (offer.annualFee === '$0') reasons.push('no annual fee');
  if (offer.signupBonus) reasons.push('has signup bonus');
  if (offer.creditMin <= 600) reasons.push('accessible credit requirements');
  if (offer.studentFriendly) reasons.push('student-friendly');
  
  if (score >= 90) {
    return `Excellent match: ${reasons.slice(0, 2).join(', ')}. High approval odds for most profiles.`;
  } else if (score >= 80) {
    return `Strong match: ${reasons.slice(0, 2).join(', ')}. Good fit for typical applicants.`;
  } else {
    return `Suitable option: ${reasons[0] || 'standard terms'}. Review requirements before applying.`;
  }
}
